#ifndef FMADIO_RING_FFI_H
#define FMADIO_RING_FFI_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Ring buffer version identifier
 */
#define FMADRING_VERSION 256

/**
 * Maximum packet payload size (10KB)
 */
#define FMADRING_ENTRYSIZE (10 * 1024)

/**
 * Ring buffer entry count
 */
#define FMADRING_ENTRYCNT 1024

/**
 * Total mmap size (16MB)
 */
#define FMADRING_MAPSIZE ((16 * 1024) * 1024)

/**
 * Page size for alignment
 */
#define PAGE_SIZE 4096

/**
 * Header size (3 pages: metadata + put + get)
 */
#define HEADER_SIZE (3 * PAGE_SIZE)

/**
 * Size of each packet entry including padding (12KB aligned to 4KB page)
 */
#define PACKET_ENTRY_SIZE (12 * 1024)

/**
 * End of stream marker (bit 0)
 */
#define FMADRING_FLAG_EOF (1 << 0)

/**
 * Frame Check Sequence error (bit 1)
 */
#define FMADRING_FLAG_FCSERR (1 << 1)

/**
 * FMADIO ring buffer capture handle
 */
typedef struct FmadioRingCapture FmadioRingCapture;

/**
 * FMADIO ring packet structure (matches fFMADRingPacket_t)
 * Total size: 12KB (10KB payload + 24 byte header + 2024 byte padding)
 */
typedef struct FmadioRingPacket FmadioRingPacket;

/**
 * Per-thread capture context
 *
 * This structure is allocated in ThreadInit and passed to all thread callbacks.
 * It holds the ring buffer handle and statistics.
 */
typedef struct FmadioThreadVars {
  /**
   * Ring buffer capture handle (Box pointer, owned)
   */
  struct FmadioRingCapture *ring;
  /**
   * Suricata ThreadVars pointer (opaque)
   */
  void *tv;
  /**
   * Next slot in the processing pipeline (TmSlot*)
   */
  void *slot;
  /**
   * Ring buffer path (owned C string)
   */
  char *ring_path;
  /**
   * Packets received counter
   */
  uint64_t pkts;
  /**
   * Bytes received counter
   */
  uint64_t bytes;
  /**
   * Packets dropped (ring overrun, etc.)
   */
  uint64_t drops;
  /**
   * Suricata stats counter ID for packets
   */
  uint16_t counter_pkts;
  /**
   * Suricata stats counter ID for bytes
   */
  uint16_t counter_bytes;
  /**
   * Suricata stats counter ID for drops
   */
  uint16_t counter_drops;
  /**
   * Flag to signal loop should break
   */
  bool break_loop;
} FmadioThreadVars;

extern void fmadio_packet_pool_wait(void);

extern void *fmadio_packet_get_from_queue_or_alloc(void);

extern void fmadio_return_packet_to_pool(void *tv, void *p);

extern void fmadio_packet_set_source(void *p, uint8_t src);

extern void fmadio_packet_set_datalink(void *p, int datalink);

extern int fmadio_packet_set_data(void *p, const uint8_t *data, uint32_t len);

extern void fmadio_packet_set_time(void *p, uint64_t secs, uint32_t usecs);

extern void fmadio_threads_set_flag(void *tv, uint32_t flag);

extern int fmadio_slot_process_pkt(void *tv, void *slot, void *p);

extern void fmadio_capture_handle_timeout(void *tv, void *p);

extern uint16_t fmadio_stats_register_counter(const char *name, void *tv);

extern void fmadio_stats_set_ui64(void *tv, uint16_t counter, uint64_t value);

extern void fmadio_stats_sync_if_signalled(void *tv);

extern void fmadio_log_notice(const char *msg);

extern void fmadio_log_error(const char *msg);

extern int fmadio_should_stop(void);

/**
 * Thread initialization callback.
 *
 * Called when a worker thread starts. Allocates thread context and opens
 * the FMADIO ring buffer.
 *
 * # Arguments
 * * `tv` - Suricata ThreadVars pointer
 * * `initdata` - Ring buffer path as C string (from capture-plugin-args)
 * * `data` - Output pointer to store allocated thread context
 *
 * # Returns
 * * `TM_ECODE_OK` on success
 * * `TM_ECODE_FAILED` on error
 */
 int fmadio_thread_init(void *tv, const void *initdata, void **data);

/**
 * Main packet acquisition loop.
 *
 * Called by Suricata to run the capture loop. Reads packets from the
 * FMADIO ring buffer and passes them through the processing pipeline.
 *
 * # Arguments
 * * `tv` - Suricata ThreadVars pointer
 * * `data` - Thread context (FmadioThreadVars)
 * * `slot` - Current TmSlot in the pipeline
 *
 * # Returns
 * * `TM_ECODE_OK` on normal exit
 * * `TM_ECODE_FAILED` on error
 */
 int fmadio_pkt_acq_loop(void *tv, void *data, void *slot);

/**
 * Signal the acquisition loop to break.
 *
 * Called when Suricata wants to stop the capture.
 *
 * # Arguments
 * * `tv` - Suricata ThreadVars pointer
 * * `data` - Thread context (FmadioThreadVars)
 *
 * # Returns
 * * `TM_ECODE_OK` always
 */
 int fmadio_pkt_acq_break_loop(void *_tv, void *data);

/**
 * Thread deinitialization callback.
 *
 * Called when a worker thread exits. Cleans up resources.
 *
 * # Arguments
 * * `tv` - Suricata ThreadVars pointer
 * * `data` - Thread context (FmadioThreadVars)
 *
 * # Returns
 * * `TM_ECODE_OK` always
 */
 int fmadio_thread_deinit(void *_tv, void *data);

/**
 * Print thread statistics on exit.
 *
 * Called when the thread exits to log final statistics.
 *
 * # Arguments
 * * `tv` - Suricata ThreadVars pointer
 * * `data` - Thread context (FmadioThreadVars)
 */
 void fmadio_thread_exit_print_stats(void *tv, void *data);

#endif /* FMADIO_RING_FFI_H */
